electrum_server = "127.0.0.1:60401"
network = "testnet"
block_time = 2
testing_mode = true
# log_file = "log/output.log" # Comment out for stdout

# Fees
fee_address = "bcrt1qjjwk2rk7nuxt6c79tsxthf5rpnky0sdhjr493x"
fee_deposit = 300
fee_withdraw = 300

# Swap parameters
punishment_duration = "3600" # 1 hour
batch_lifetime = "3600" # 1 hour

#Mainstay config
mainstay_config = ""
